# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}-${{ hashFiles('**/*.wixproj') }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build application
      run: dotnet build --no-restore --verbosity normal Lanpartyseating.Desktop --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal Lanpartyseating.Desktop.Tests --configuration Release
    - name: Build
      run: dotnet build LanpartySeating.Desktop.Installer/LanpartySeating.Desktop.Installer.wixproj --configuration Release --property:Version=1.0.20
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: LanpartySeating.Desktop.Installer
        path: |
          LanpartySeating.Desktop.Installer/bin/Release/LanpartySeating.Desktop.Installer.msi
          LanpartySeating.Desktop.Installer/bin/Release/LanpartySeating.Desktop.Installer.wixpdb
